provider: onelogin
major-version: 1
makeTemplate: bridged
plugins:
  - name: terraform
    version: "1.0.16"
    kind: converter

  - name: random 
    version: "2.2.0"
team: ecosystem
pulumiConvert: 1
