// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Onelogin
{
    public static class GetPrivilegesInstance
    {
        public static Task<GetPrivilegesInstanceResult> InvokeAsync(GetPrivilegesInstanceArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetPrivilegesInstanceResult>("onelogin:index/getPrivilegesInstance:getPrivilegesInstance", args ?? new GetPrivilegesInstanceArgs(), options.WithDefaults());

        public static Output<GetPrivilegesInstanceResult> Invoke(GetPrivilegesInstanceInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetPrivilegesInstanceResult>("onelogin:index/getPrivilegesInstance:getPrivilegesInstance", args ?? new GetPrivilegesInstanceInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetPrivilegesInstanceArgs : global::Pulumi.InvokeArgs
    {
        [Input("description")]
        public string? Description { get; set; }

        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        [Input("name")]
        public string? Name { get; set; }

        [Input("privilege")]
        public Inputs.GetPrivilegesInstancePrivilegeArgs? Privilege { get; set; }

        public GetPrivilegesInstanceArgs()
        {
        }
        public static new GetPrivilegesInstanceArgs Empty => new GetPrivilegesInstanceArgs();
    }

    public sealed class GetPrivilegesInstanceInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("privilege")]
        public Input<Inputs.GetPrivilegesInstancePrivilegeInputArgs>? Privilege { get; set; }

        public GetPrivilegesInstanceInvokeArgs()
        {
        }
        public static new GetPrivilegesInstanceInvokeArgs Empty => new GetPrivilegesInstanceInvokeArgs();
    }


    [OutputType]
    public sealed class GetPrivilegesInstanceResult
    {
        public readonly string Description;
        public readonly string Id;
        public readonly string Name;
        public readonly Outputs.GetPrivilegesInstancePrivilegeResult Privilege;

        [OutputConstructor]
        private GetPrivilegesInstanceResult(
            string description,

            string id,

            string name,

            Outputs.GetPrivilegesInstancePrivilegeResult privilege)
        {
            Description = description;
            Id = id;
            Name = name;
            Privilege = privilege;
        }
    }
}
