// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Immutable;

namespace Pulumi.Onelogin
{
    public static class Config
    {
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "IDE1006", Justification = 
        "Double underscore prefix used to avoid conflicts with variable names.")]
        private sealed class __Value<T>
        {
            private readonly Func<T> _getter;
            private T _value = default!;
            private bool _set;

            public __Value(Func<T> getter)
            {
                _getter = getter;
            }

            public T Get() => _set ? _value : _getter();

            public void Set(T value)
            {
                _value = value;
                _set = true;
            }
        }

        private static readonly global::Pulumi.Config __config = new global::Pulumi.Config("onelogin");

        private static readonly __Value<string?> _apikeyAuth = new __Value<string?>(() => __config.Get("apikeyAuth"));
        public static string? ApikeyAuth
        {
            get => _apikeyAuth.Get();
            set => _apikeyAuth.Set(value);
        }

        private static readonly __Value<string?> _contentType = new __Value<string?>(() => __config.Get("contentType"));
        public static string? ContentType
        {
            get => _contentType.Get();
            set => _contentType.Set(value);
        }

        private static readonly __Value<ImmutableArray<Pulumi.Onelogin.Config.Types.Endpoints>> _endpoints = new __Value<ImmutableArray<Pulumi.Onelogin.Config.Types.Endpoints>>(() => __config.GetObject<ImmutableArray<Pulumi.Onelogin.Config.Types.Endpoints>>("endpoints"));
        public static ImmutableArray<Pulumi.Onelogin.Config.Types.Endpoints> Endpoints
        {
            get => _endpoints.Get();
            set => _endpoints.Set(value);
        }

        public static class Types
        {

             public class Endpoints
             {
                public string? Apps { get; set; } = null!;
                public string? AppsRules { get; set; } = null!;
                public string? AuthServers { get; set; } = null!;
                public string? Privileges { get; set; } = null!;
                public string? RiskRules { get; set; } = null!;
                public string? Roles { get; set; } = null!;
                public string? Users { get; set; } = null!;
                public string? UsersV1 { get; set; } = null!;
            }
        }
    }
}
