// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package apps

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-onelogin/sdk/go/onelogin/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetInstance(ctx *pulumi.Context, args *GetInstanceArgs, opts ...pulumi.InvokeOption) (*GetInstanceResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetInstanceResult
	err := ctx.Invoke("onelogin:apps/getInstance:getInstance", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getInstance.
type GetInstanceArgs struct {
	AllowAssumedSignin    *bool                        `pulumi:"allowAssumedSignin"`
	AuthMethod            *int                         `pulumi:"authMethod"`
	AuthMethodDescription *string                      `pulumi:"authMethodDescription"`
	BrandId               *int                         `pulumi:"brandId"`
	Configuration         *GetInstanceConfiguration    `pulumi:"configuration"`
	ConnectorId           *int                         `pulumi:"connectorId"`
	CreatedAt             *string                      `pulumi:"createdAt"`
	Description           *string                      `pulumi:"description"`
	EnforcementPoint      *GetInstanceEnforcementPoint `pulumi:"enforcementPoint"`
	IconUrl               *string                      `pulumi:"iconUrl"`
	Id                    string                       `pulumi:"id"`
	LoginConfig           *int                         `pulumi:"loginConfig"`
	Name                  *string                      `pulumi:"name"`
	Notes                 *string                      `pulumi:"notes"`
	Parameters            *GetInstanceParameters       `pulumi:"parameters"`
	PolicyId              *int                         `pulumi:"policyId"`
	Provisioning          *GetInstanceProvisioning     `pulumi:"provisioning"`
	RoleIds               []int                        `pulumi:"roleIds"`
	Sso                   *GetInstanceSso              `pulumi:"sso"`
	TabId                 *int                         `pulumi:"tabId"`
	UpdatedAt             *string                      `pulumi:"updatedAt"`
	Visible               *bool                        `pulumi:"visible"`
}

// A collection of values returned by getInstance.
type GetInstanceResult struct {
	AllowAssumedSignin    bool                        `pulumi:"allowAssumedSignin"`
	AuthMethod            int                         `pulumi:"authMethod"`
	AuthMethodDescription string                      `pulumi:"authMethodDescription"`
	BrandId               int                         `pulumi:"brandId"`
	Configuration         GetInstanceConfiguration    `pulumi:"configuration"`
	ConnectorId           int                         `pulumi:"connectorId"`
	CreatedAt             string                      `pulumi:"createdAt"`
	Description           string                      `pulumi:"description"`
	EnforcementPoint      GetInstanceEnforcementPoint `pulumi:"enforcementPoint"`
	IconUrl               string                      `pulumi:"iconUrl"`
	Id                    string                      `pulumi:"id"`
	LoginConfig           int                         `pulumi:"loginConfig"`
	Name                  string                      `pulumi:"name"`
	Notes                 string                      `pulumi:"notes"`
	Parameters            GetInstanceParameters       `pulumi:"parameters"`
	PolicyId              int                         `pulumi:"policyId"`
	Provisioning          GetInstanceProvisioning     `pulumi:"provisioning"`
	RoleIds               []int                       `pulumi:"roleIds"`
	Sso                   GetInstanceSso              `pulumi:"sso"`
	TabId                 int                         `pulumi:"tabId"`
	UpdatedAt             string                      `pulumi:"updatedAt"`
	Visible               bool                        `pulumi:"visible"`
}

func GetInstanceOutput(ctx *pulumi.Context, args GetInstanceOutputArgs, opts ...pulumi.InvokeOption) GetInstanceResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetInstanceResult, error) {
			args := v.(GetInstanceArgs)
			r, err := GetInstance(ctx, &args, opts...)
			var s GetInstanceResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetInstanceResultOutput)
}

// A collection of arguments for invoking getInstance.
type GetInstanceOutputArgs struct {
	AllowAssumedSignin    pulumi.BoolPtrInput                 `pulumi:"allowAssumedSignin"`
	AuthMethod            pulumi.IntPtrInput                  `pulumi:"authMethod"`
	AuthMethodDescription pulumi.StringPtrInput               `pulumi:"authMethodDescription"`
	BrandId               pulumi.IntPtrInput                  `pulumi:"brandId"`
	Configuration         GetInstanceConfigurationPtrInput    `pulumi:"configuration"`
	ConnectorId           pulumi.IntPtrInput                  `pulumi:"connectorId"`
	CreatedAt             pulumi.StringPtrInput               `pulumi:"createdAt"`
	Description           pulumi.StringPtrInput               `pulumi:"description"`
	EnforcementPoint      GetInstanceEnforcementPointPtrInput `pulumi:"enforcementPoint"`
	IconUrl               pulumi.StringPtrInput               `pulumi:"iconUrl"`
	Id                    pulumi.StringInput                  `pulumi:"id"`
	LoginConfig           pulumi.IntPtrInput                  `pulumi:"loginConfig"`
	Name                  pulumi.StringPtrInput               `pulumi:"name"`
	Notes                 pulumi.StringPtrInput               `pulumi:"notes"`
	Parameters            GetInstanceParametersPtrInput       `pulumi:"parameters"`
	PolicyId              pulumi.IntPtrInput                  `pulumi:"policyId"`
	Provisioning          GetInstanceProvisioningPtrInput     `pulumi:"provisioning"`
	RoleIds               pulumi.IntArrayInput                `pulumi:"roleIds"`
	Sso                   GetInstanceSsoPtrInput              `pulumi:"sso"`
	TabId                 pulumi.IntPtrInput                  `pulumi:"tabId"`
	UpdatedAt             pulumi.StringPtrInput               `pulumi:"updatedAt"`
	Visible               pulumi.BoolPtrInput                 `pulumi:"visible"`
}

func (GetInstanceOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetInstanceArgs)(nil)).Elem()
}

// A collection of values returned by getInstance.
type GetInstanceResultOutput struct{ *pulumi.OutputState }

func (GetInstanceResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetInstanceResult)(nil)).Elem()
}

func (o GetInstanceResultOutput) ToGetInstanceResultOutput() GetInstanceResultOutput {
	return o
}

func (o GetInstanceResultOutput) ToGetInstanceResultOutputWithContext(ctx context.Context) GetInstanceResultOutput {
	return o
}

func (o GetInstanceResultOutput) AllowAssumedSignin() pulumi.BoolOutput {
	return o.ApplyT(func(v GetInstanceResult) bool { return v.AllowAssumedSignin }).(pulumi.BoolOutput)
}

func (o GetInstanceResultOutput) AuthMethod() pulumi.IntOutput {
	return o.ApplyT(func(v GetInstanceResult) int { return v.AuthMethod }).(pulumi.IntOutput)
}

func (o GetInstanceResultOutput) AuthMethodDescription() pulumi.StringOutput {
	return o.ApplyT(func(v GetInstanceResult) string { return v.AuthMethodDescription }).(pulumi.StringOutput)
}

func (o GetInstanceResultOutput) BrandId() pulumi.IntOutput {
	return o.ApplyT(func(v GetInstanceResult) int { return v.BrandId }).(pulumi.IntOutput)
}

func (o GetInstanceResultOutput) Configuration() GetInstanceConfigurationOutput {
	return o.ApplyT(func(v GetInstanceResult) GetInstanceConfiguration { return v.Configuration }).(GetInstanceConfigurationOutput)
}

func (o GetInstanceResultOutput) ConnectorId() pulumi.IntOutput {
	return o.ApplyT(func(v GetInstanceResult) int { return v.ConnectorId }).(pulumi.IntOutput)
}

func (o GetInstanceResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v GetInstanceResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

func (o GetInstanceResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v GetInstanceResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o GetInstanceResultOutput) EnforcementPoint() GetInstanceEnforcementPointOutput {
	return o.ApplyT(func(v GetInstanceResult) GetInstanceEnforcementPoint { return v.EnforcementPoint }).(GetInstanceEnforcementPointOutput)
}

func (o GetInstanceResultOutput) IconUrl() pulumi.StringOutput {
	return o.ApplyT(func(v GetInstanceResult) string { return v.IconUrl }).(pulumi.StringOutput)
}

func (o GetInstanceResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetInstanceResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetInstanceResultOutput) LoginConfig() pulumi.IntOutput {
	return o.ApplyT(func(v GetInstanceResult) int { return v.LoginConfig }).(pulumi.IntOutput)
}

func (o GetInstanceResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetInstanceResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o GetInstanceResultOutput) Notes() pulumi.StringOutput {
	return o.ApplyT(func(v GetInstanceResult) string { return v.Notes }).(pulumi.StringOutput)
}

func (o GetInstanceResultOutput) Parameters() GetInstanceParametersOutput {
	return o.ApplyT(func(v GetInstanceResult) GetInstanceParameters { return v.Parameters }).(GetInstanceParametersOutput)
}

func (o GetInstanceResultOutput) PolicyId() pulumi.IntOutput {
	return o.ApplyT(func(v GetInstanceResult) int { return v.PolicyId }).(pulumi.IntOutput)
}

func (o GetInstanceResultOutput) Provisioning() GetInstanceProvisioningOutput {
	return o.ApplyT(func(v GetInstanceResult) GetInstanceProvisioning { return v.Provisioning }).(GetInstanceProvisioningOutput)
}

func (o GetInstanceResultOutput) RoleIds() pulumi.IntArrayOutput {
	return o.ApplyT(func(v GetInstanceResult) []int { return v.RoleIds }).(pulumi.IntArrayOutput)
}

func (o GetInstanceResultOutput) Sso() GetInstanceSsoOutput {
	return o.ApplyT(func(v GetInstanceResult) GetInstanceSso { return v.Sso }).(GetInstanceSsoOutput)
}

func (o GetInstanceResultOutput) TabId() pulumi.IntOutput {
	return o.ApplyT(func(v GetInstanceResult) int { return v.TabId }).(pulumi.IntOutput)
}

func (o GetInstanceResultOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v GetInstanceResult) string { return v.UpdatedAt }).(pulumi.StringOutput)
}

func (o GetInstanceResultOutput) Visible() pulumi.BoolOutput {
	return o.ApplyT(func(v GetInstanceResult) bool { return v.Visible }).(pulumi.BoolOutput)
}

func init() {
	pulumi.RegisterOutputType(GetInstanceResultOutput{})
}
