// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.onelogin.users.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetUsersArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetUsersArgs Empty = new GetUsersArgs();

    @Import(name="directoryId")
    private @Nullable Output<Integer> directoryId;

    public Optional<Output<Integer>> directoryId() {
        return Optional.ofNullable(this.directoryId);
    }

    @Import(name="externalId")
    private @Nullable Output<Integer> externalId;

    public Optional<Output<Integer>> externalId() {
        return Optional.ofNullable(this.externalId);
    }

    @Import(name="firstname")
    private @Nullable Output<String> firstname;

    public Optional<Output<String>> firstname() {
        return Optional.ofNullable(this.firstname);
    }

    @Import(name="lastname")
    private @Nullable Output<String> lastname;

    public Optional<Output<String>> lastname() {
        return Optional.ofNullable(this.lastname);
    }

    @Import(name="samaccountname")
    private @Nullable Output<String> samaccountname;

    public Optional<Output<String>> samaccountname() {
        return Optional.ofNullable(this.samaccountname);
    }

    @Import(name="userId")
    private @Nullable Output<String> userId;

    public Optional<Output<String>> userId() {
        return Optional.ofNullable(this.userId);
    }

    @Import(name="username")
    private @Nullable Output<String> username;

    public Optional<Output<String>> username() {
        return Optional.ofNullable(this.username);
    }

    private GetUsersArgs() {}

    private GetUsersArgs(GetUsersArgs $) {
        this.directoryId = $.directoryId;
        this.externalId = $.externalId;
        this.firstname = $.firstname;
        this.lastname = $.lastname;
        this.samaccountname = $.samaccountname;
        this.userId = $.userId;
        this.username = $.username;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetUsersArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetUsersArgs $;

        public Builder() {
            $ = new GetUsersArgs();
        }

        public Builder(GetUsersArgs defaults) {
            $ = new GetUsersArgs(Objects.requireNonNull(defaults));
        }

        public Builder directoryId(@Nullable Output<Integer> directoryId) {
            $.directoryId = directoryId;
            return this;
        }

        public Builder directoryId(Integer directoryId) {
            return directoryId(Output.of(directoryId));
        }

        public Builder externalId(@Nullable Output<Integer> externalId) {
            $.externalId = externalId;
            return this;
        }

        public Builder externalId(Integer externalId) {
            return externalId(Output.of(externalId));
        }

        public Builder firstname(@Nullable Output<String> firstname) {
            $.firstname = firstname;
            return this;
        }

        public Builder firstname(String firstname) {
            return firstname(Output.of(firstname));
        }

        public Builder lastname(@Nullable Output<String> lastname) {
            $.lastname = lastname;
            return this;
        }

        public Builder lastname(String lastname) {
            return lastname(Output.of(lastname));
        }

        public Builder samaccountname(@Nullable Output<String> samaccountname) {
            $.samaccountname = samaccountname;
            return this;
        }

        public Builder samaccountname(String samaccountname) {
            return samaccountname(Output.of(samaccountname));
        }

        public Builder userId(@Nullable Output<String> userId) {
            $.userId = userId;
            return this;
        }

        public Builder userId(String userId) {
            return userId(Output.of(userId));
        }

        public Builder username(@Nullable Output<String> username) {
            $.username = username;
            return this;
        }

        public Builder username(String username) {
            return username(Output.of(username));
        }

        public GetUsersArgs build() {
            return $;
        }
    }

}
