// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package users

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-onelogin/sdk/go/onelogin/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetDevices(ctx *pulumi.Context, args *GetDevicesArgs, opts ...pulumi.InvokeOption) (*GetDevicesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetDevicesResult
	err := ctx.Invoke("onelogin:users/getDevices:getDevices", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getDevices.
type GetDevicesArgs struct {
	AuthFactorName  *string            `pulumi:"authFactorName"`
	Default         *bool              `pulumi:"default"`
	DeviceId        *string            `pulumi:"deviceId"`
	Filters         []GetDevicesFilter `pulumi:"filters"`
	TypeDisplayName *string            `pulumi:"typeDisplayName"`
	UserDisplayName *string            `pulumi:"userDisplayName"`
	UsersId         string             `pulumi:"usersId"`
}

// A collection of values returned by getDevices.
type GetDevicesResult struct {
	AuthFactorName string             `pulumi:"authFactorName"`
	Default        bool               `pulumi:"default"`
	DeviceId       string             `pulumi:"deviceId"`
	Filters        []GetDevicesFilter `pulumi:"filters"`
	// The provider-assigned unique ID for this managed resource.
	Id              string `pulumi:"id"`
	TypeDisplayName string `pulumi:"typeDisplayName"`
	UserDisplayName string `pulumi:"userDisplayName"`
	UsersId         string `pulumi:"usersId"`
}

func GetDevicesOutput(ctx *pulumi.Context, args GetDevicesOutputArgs, opts ...pulumi.InvokeOption) GetDevicesResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetDevicesResult, error) {
			args := v.(GetDevicesArgs)
			r, err := GetDevices(ctx, &args, opts...)
			var s GetDevicesResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetDevicesResultOutput)
}

// A collection of arguments for invoking getDevices.
type GetDevicesOutputArgs struct {
	AuthFactorName  pulumi.StringPtrInput      `pulumi:"authFactorName"`
	Default         pulumi.BoolPtrInput        `pulumi:"default"`
	DeviceId        pulumi.StringPtrInput      `pulumi:"deviceId"`
	Filters         GetDevicesFilterArrayInput `pulumi:"filters"`
	TypeDisplayName pulumi.StringPtrInput      `pulumi:"typeDisplayName"`
	UserDisplayName pulumi.StringPtrInput      `pulumi:"userDisplayName"`
	UsersId         pulumi.StringInput         `pulumi:"usersId"`
}

func (GetDevicesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDevicesArgs)(nil)).Elem()
}

// A collection of values returned by getDevices.
type GetDevicesResultOutput struct{ *pulumi.OutputState }

func (GetDevicesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDevicesResult)(nil)).Elem()
}

func (o GetDevicesResultOutput) ToGetDevicesResultOutput() GetDevicesResultOutput {
	return o
}

func (o GetDevicesResultOutput) ToGetDevicesResultOutputWithContext(ctx context.Context) GetDevicesResultOutput {
	return o
}

func (o GetDevicesResultOutput) AuthFactorName() pulumi.StringOutput {
	return o.ApplyT(func(v GetDevicesResult) string { return v.AuthFactorName }).(pulumi.StringOutput)
}

func (o GetDevicesResultOutput) Default() pulumi.BoolOutput {
	return o.ApplyT(func(v GetDevicesResult) bool { return v.Default }).(pulumi.BoolOutput)
}

func (o GetDevicesResultOutput) DeviceId() pulumi.StringOutput {
	return o.ApplyT(func(v GetDevicesResult) string { return v.DeviceId }).(pulumi.StringOutput)
}

func (o GetDevicesResultOutput) Filters() GetDevicesFilterArrayOutput {
	return o.ApplyT(func(v GetDevicesResult) []GetDevicesFilter { return v.Filters }).(GetDevicesFilterArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetDevicesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetDevicesResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetDevicesResultOutput) TypeDisplayName() pulumi.StringOutput {
	return o.ApplyT(func(v GetDevicesResult) string { return v.TypeDisplayName }).(pulumi.StringOutput)
}

func (o GetDevicesResultOutput) UserDisplayName() pulumi.StringOutput {
	return o.ApplyT(func(v GetDevicesResult) string { return v.UserDisplayName }).(pulumi.StringOutput)
}

func (o GetDevicesResultOutput) UsersId() pulumi.StringOutput {
	return o.ApplyT(func(v GetDevicesResult) string { return v.UsersId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetDevicesResultOutput{})
}
