// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package users

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-onelogin/sdk/go/onelogin/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

func LookupV1(ctx *pulumi.Context, args *LookupV1Args, opts ...pulumi.InvokeOption) (*LookupV1Result, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupV1Result
	err := ctx.Invoke("onelogin:users/getV1:getV1", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getV1.
type LookupV1Args struct {
	ActivatedAt          *string       `pulumi:"activatedAt"`
	Comment              *string       `pulumi:"comment"`
	Company              *string       `pulumi:"company"`
	CreatedAt            *string       `pulumi:"createdAt"`
	Department           *string       `pulumi:"department"`
	DirectoryId          *int          `pulumi:"directoryId"`
	DistinguishedName    *string       `pulumi:"distinguishedName"`
	Email                *string       `pulumi:"email"`
	ExternalId           *string       `pulumi:"externalId"`
	Filters              []GetV1Filter `pulumi:"filters"`
	Firstname            *string       `pulumi:"firstname"`
	GroupId              *int          `pulumi:"groupId"`
	InvalidLoginAttempts *int          `pulumi:"invalidLoginAttempts"`
	InvitationSentAt     *string       `pulumi:"invitationSentAt"`
	LastLogin            *string       `pulumi:"lastLogin"`
	Lastname             *string       `pulumi:"lastname"`
	LockedUntil          *string       `pulumi:"lockedUntil"`
	ManagerAdId          *string       `pulumi:"managerAdId"`
	ManagerUserId        *string       `pulumi:"managerUserId"`
	MemberOf             *string       `pulumi:"memberOf"`
	Password             *string       `pulumi:"password"`
	PasswordAlgorithm    *string       `pulumi:"passwordAlgorithm"`
	PasswordChangedAt    *string       `pulumi:"passwordChangedAt"`
	PasswordConfirmation *string       `pulumi:"passwordConfirmation"`
	Phone                *string       `pulumi:"phone"`
	PreferredLocaleCode  *string       `pulumi:"preferredLocaleCode"`
	RoleIds              []int         `pulumi:"roleIds"`
	Salt                 *string       `pulumi:"salt"`
	Samaccountname       *string       `pulumi:"samaccountname"`
	State                *int          `pulumi:"state"`
	Status               *int          `pulumi:"status"`
	Title                *string       `pulumi:"title"`
	TrustedIdpId         *int          `pulumi:"trustedIdpId"`
	UpdatedAt            *string       `pulumi:"updatedAt"`
	Username             *string       `pulumi:"username"`
	Userprincipalname    *string       `pulumi:"userprincipalname"`
}

// A collection of values returned by getV1.
type LookupV1Result struct {
	ActivatedAt       string        `pulumi:"activatedAt"`
	Comment           string        `pulumi:"comment"`
	Company           string        `pulumi:"company"`
	CreatedAt         string        `pulumi:"createdAt"`
	Department        string        `pulumi:"department"`
	DirectoryId       int           `pulumi:"directoryId"`
	DistinguishedName string        `pulumi:"distinguishedName"`
	Email             string        `pulumi:"email"`
	ExternalId        string        `pulumi:"externalId"`
	Filters           []GetV1Filter `pulumi:"filters"`
	Firstname         string        `pulumi:"firstname"`
	GroupId           int           `pulumi:"groupId"`
	// The provider-assigned unique ID for this managed resource.
	Id                   string `pulumi:"id"`
	InvalidLoginAttempts int    `pulumi:"invalidLoginAttempts"`
	InvitationSentAt     string `pulumi:"invitationSentAt"`
	LastLogin            string `pulumi:"lastLogin"`
	Lastname             string `pulumi:"lastname"`
	LockedUntil          string `pulumi:"lockedUntil"`
	ManagerAdId          string `pulumi:"managerAdId"`
	ManagerUserId        string `pulumi:"managerUserId"`
	MemberOf             string `pulumi:"memberOf"`
	Password             string `pulumi:"password"`
	PasswordAlgorithm    string `pulumi:"passwordAlgorithm"`
	PasswordChangedAt    string `pulumi:"passwordChangedAt"`
	PasswordConfirmation string `pulumi:"passwordConfirmation"`
	Phone                string `pulumi:"phone"`
	PreferredLocaleCode  string `pulumi:"preferredLocaleCode"`
	RoleIds              []int  `pulumi:"roleIds"`
	Salt                 string `pulumi:"salt"`
	Samaccountname       string `pulumi:"samaccountname"`
	State                int    `pulumi:"state"`
	Status               int    `pulumi:"status"`
	Title                string `pulumi:"title"`
	TrustedIdpId         int    `pulumi:"trustedIdpId"`
	UpdatedAt            string `pulumi:"updatedAt"`
	Username             string `pulumi:"username"`
	Userprincipalname    string `pulumi:"userprincipalname"`
}

func LookupV1Output(ctx *pulumi.Context, args LookupV1OutputArgs, opts ...pulumi.InvokeOption) LookupV1ResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupV1Result, error) {
			args := v.(LookupV1Args)
			r, err := LookupV1(ctx, &args, opts...)
			var s LookupV1Result
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupV1ResultOutput)
}

// A collection of arguments for invoking getV1.
type LookupV1OutputArgs struct {
	ActivatedAt          pulumi.StringPtrInput `pulumi:"activatedAt"`
	Comment              pulumi.StringPtrInput `pulumi:"comment"`
	Company              pulumi.StringPtrInput `pulumi:"company"`
	CreatedAt            pulumi.StringPtrInput `pulumi:"createdAt"`
	Department           pulumi.StringPtrInput `pulumi:"department"`
	DirectoryId          pulumi.IntPtrInput    `pulumi:"directoryId"`
	DistinguishedName    pulumi.StringPtrInput `pulumi:"distinguishedName"`
	Email                pulumi.StringPtrInput `pulumi:"email"`
	ExternalId           pulumi.StringPtrInput `pulumi:"externalId"`
	Filters              GetV1FilterArrayInput `pulumi:"filters"`
	Firstname            pulumi.StringPtrInput `pulumi:"firstname"`
	GroupId              pulumi.IntPtrInput    `pulumi:"groupId"`
	InvalidLoginAttempts pulumi.IntPtrInput    `pulumi:"invalidLoginAttempts"`
	InvitationSentAt     pulumi.StringPtrInput `pulumi:"invitationSentAt"`
	LastLogin            pulumi.StringPtrInput `pulumi:"lastLogin"`
	Lastname             pulumi.StringPtrInput `pulumi:"lastname"`
	LockedUntil          pulumi.StringPtrInput `pulumi:"lockedUntil"`
	ManagerAdId          pulumi.StringPtrInput `pulumi:"managerAdId"`
	ManagerUserId        pulumi.StringPtrInput `pulumi:"managerUserId"`
	MemberOf             pulumi.StringPtrInput `pulumi:"memberOf"`
	Password             pulumi.StringPtrInput `pulumi:"password"`
	PasswordAlgorithm    pulumi.StringPtrInput `pulumi:"passwordAlgorithm"`
	PasswordChangedAt    pulumi.StringPtrInput `pulumi:"passwordChangedAt"`
	PasswordConfirmation pulumi.StringPtrInput `pulumi:"passwordConfirmation"`
	Phone                pulumi.StringPtrInput `pulumi:"phone"`
	PreferredLocaleCode  pulumi.StringPtrInput `pulumi:"preferredLocaleCode"`
	RoleIds              pulumi.IntArrayInput  `pulumi:"roleIds"`
	Salt                 pulumi.StringPtrInput `pulumi:"salt"`
	Samaccountname       pulumi.StringPtrInput `pulumi:"samaccountname"`
	State                pulumi.IntPtrInput    `pulumi:"state"`
	Status               pulumi.IntPtrInput    `pulumi:"status"`
	Title                pulumi.StringPtrInput `pulumi:"title"`
	TrustedIdpId         pulumi.IntPtrInput    `pulumi:"trustedIdpId"`
	UpdatedAt            pulumi.StringPtrInput `pulumi:"updatedAt"`
	Username             pulumi.StringPtrInput `pulumi:"username"`
	Userprincipalname    pulumi.StringPtrInput `pulumi:"userprincipalname"`
}

func (LookupV1OutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupV1Args)(nil)).Elem()
}

// A collection of values returned by getV1.
type LookupV1ResultOutput struct{ *pulumi.OutputState }

func (LookupV1ResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupV1Result)(nil)).Elem()
}

func (o LookupV1ResultOutput) ToLookupV1ResultOutput() LookupV1ResultOutput {
	return o
}

func (o LookupV1ResultOutput) ToLookupV1ResultOutputWithContext(ctx context.Context) LookupV1ResultOutput {
	return o
}

func (o LookupV1ResultOutput) ToOutput(ctx context.Context) pulumix.Output[LookupV1Result] {
	return pulumix.Output[LookupV1Result]{
		OutputState: o.OutputState,
	}
}

func (o LookupV1ResultOutput) ActivatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupV1Result) string { return v.ActivatedAt }).(pulumi.StringOutput)
}

func (o LookupV1ResultOutput) Comment() pulumi.StringOutput {
	return o.ApplyT(func(v LookupV1Result) string { return v.Comment }).(pulumi.StringOutput)
}

func (o LookupV1ResultOutput) Company() pulumi.StringOutput {
	return o.ApplyT(func(v LookupV1Result) string { return v.Company }).(pulumi.StringOutput)
}

func (o LookupV1ResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupV1Result) string { return v.CreatedAt }).(pulumi.StringOutput)
}

func (o LookupV1ResultOutput) Department() pulumi.StringOutput {
	return o.ApplyT(func(v LookupV1Result) string { return v.Department }).(pulumi.StringOutput)
}

func (o LookupV1ResultOutput) DirectoryId() pulumi.IntOutput {
	return o.ApplyT(func(v LookupV1Result) int { return v.DirectoryId }).(pulumi.IntOutput)
}

func (o LookupV1ResultOutput) DistinguishedName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupV1Result) string { return v.DistinguishedName }).(pulumi.StringOutput)
}

func (o LookupV1ResultOutput) Email() pulumi.StringOutput {
	return o.ApplyT(func(v LookupV1Result) string { return v.Email }).(pulumi.StringOutput)
}

func (o LookupV1ResultOutput) ExternalId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupV1Result) string { return v.ExternalId }).(pulumi.StringOutput)
}

func (o LookupV1ResultOutput) Filters() GetV1FilterArrayOutput {
	return o.ApplyT(func(v LookupV1Result) []GetV1Filter { return v.Filters }).(GetV1FilterArrayOutput)
}

func (o LookupV1ResultOutput) Firstname() pulumi.StringOutput {
	return o.ApplyT(func(v LookupV1Result) string { return v.Firstname }).(pulumi.StringOutput)
}

func (o LookupV1ResultOutput) GroupId() pulumi.IntOutput {
	return o.ApplyT(func(v LookupV1Result) int { return v.GroupId }).(pulumi.IntOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupV1ResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupV1Result) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupV1ResultOutput) InvalidLoginAttempts() pulumi.IntOutput {
	return o.ApplyT(func(v LookupV1Result) int { return v.InvalidLoginAttempts }).(pulumi.IntOutput)
}

func (o LookupV1ResultOutput) InvitationSentAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupV1Result) string { return v.InvitationSentAt }).(pulumi.StringOutput)
}

func (o LookupV1ResultOutput) LastLogin() pulumi.StringOutput {
	return o.ApplyT(func(v LookupV1Result) string { return v.LastLogin }).(pulumi.StringOutput)
}

func (o LookupV1ResultOutput) Lastname() pulumi.StringOutput {
	return o.ApplyT(func(v LookupV1Result) string { return v.Lastname }).(pulumi.StringOutput)
}

func (o LookupV1ResultOutput) LockedUntil() pulumi.StringOutput {
	return o.ApplyT(func(v LookupV1Result) string { return v.LockedUntil }).(pulumi.StringOutput)
}

func (o LookupV1ResultOutput) ManagerAdId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupV1Result) string { return v.ManagerAdId }).(pulumi.StringOutput)
}

func (o LookupV1ResultOutput) ManagerUserId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupV1Result) string { return v.ManagerUserId }).(pulumi.StringOutput)
}

func (o LookupV1ResultOutput) MemberOf() pulumi.StringOutput {
	return o.ApplyT(func(v LookupV1Result) string { return v.MemberOf }).(pulumi.StringOutput)
}

func (o LookupV1ResultOutput) Password() pulumi.StringOutput {
	return o.ApplyT(func(v LookupV1Result) string { return v.Password }).(pulumi.StringOutput)
}

func (o LookupV1ResultOutput) PasswordAlgorithm() pulumi.StringOutput {
	return o.ApplyT(func(v LookupV1Result) string { return v.PasswordAlgorithm }).(pulumi.StringOutput)
}

func (o LookupV1ResultOutput) PasswordChangedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupV1Result) string { return v.PasswordChangedAt }).(pulumi.StringOutput)
}

func (o LookupV1ResultOutput) PasswordConfirmation() pulumi.StringOutput {
	return o.ApplyT(func(v LookupV1Result) string { return v.PasswordConfirmation }).(pulumi.StringOutput)
}

func (o LookupV1ResultOutput) Phone() pulumi.StringOutput {
	return o.ApplyT(func(v LookupV1Result) string { return v.Phone }).(pulumi.StringOutput)
}

func (o LookupV1ResultOutput) PreferredLocaleCode() pulumi.StringOutput {
	return o.ApplyT(func(v LookupV1Result) string { return v.PreferredLocaleCode }).(pulumi.StringOutput)
}

func (o LookupV1ResultOutput) RoleIds() pulumi.IntArrayOutput {
	return o.ApplyT(func(v LookupV1Result) []int { return v.RoleIds }).(pulumi.IntArrayOutput)
}

func (o LookupV1ResultOutput) Salt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupV1Result) string { return v.Salt }).(pulumi.StringOutput)
}

func (o LookupV1ResultOutput) Samaccountname() pulumi.StringOutput {
	return o.ApplyT(func(v LookupV1Result) string { return v.Samaccountname }).(pulumi.StringOutput)
}

func (o LookupV1ResultOutput) State() pulumi.IntOutput {
	return o.ApplyT(func(v LookupV1Result) int { return v.State }).(pulumi.IntOutput)
}

func (o LookupV1ResultOutput) Status() pulumi.IntOutput {
	return o.ApplyT(func(v LookupV1Result) int { return v.Status }).(pulumi.IntOutput)
}

func (o LookupV1ResultOutput) Title() pulumi.StringOutput {
	return o.ApplyT(func(v LookupV1Result) string { return v.Title }).(pulumi.StringOutput)
}

func (o LookupV1ResultOutput) TrustedIdpId() pulumi.IntOutput {
	return o.ApplyT(func(v LookupV1Result) int { return v.TrustedIdpId }).(pulumi.IntOutput)
}

func (o LookupV1ResultOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupV1Result) string { return v.UpdatedAt }).(pulumi.StringOutput)
}

func (o LookupV1ResultOutput) Username() pulumi.StringOutput {
	return o.ApplyT(func(v LookupV1Result) string { return v.Username }).(pulumi.StringOutput)
}

func (o LookupV1ResultOutput) Userprincipalname() pulumi.StringOutput {
	return o.ApplyT(func(v LookupV1Result) string { return v.Userprincipalname }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupV1ResultOutput{})
}
