// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.onelogin;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SmarthookEnvironmentVariablesArgs extends com.pulumi.resources.ResourceArgs {

    public static final SmarthookEnvironmentVariablesArgs Empty = new SmarthookEnvironmentVariablesArgs();

    @Import(name="name")
    private @Nullable Output<String> name;

    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    @Import(name="value", required=true)
    private Output<String> value;

    public Output<String> value() {
        return this.value;
    }

    private SmarthookEnvironmentVariablesArgs() {}

    private SmarthookEnvironmentVariablesArgs(SmarthookEnvironmentVariablesArgs $) {
        this.name = $.name;
        this.value = $.value;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SmarthookEnvironmentVariablesArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SmarthookEnvironmentVariablesArgs $;

        public Builder() {
            $ = new SmarthookEnvironmentVariablesArgs();
        }

        public Builder(SmarthookEnvironmentVariablesArgs defaults) {
            $ = new SmarthookEnvironmentVariablesArgs(Objects.requireNonNull(defaults));
        }

        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        public Builder value(Output<String> value) {
            $.value = value;
            return this;
        }

        public Builder value(String value) {
            return value(Output.of(value));
        }

        public SmarthookEnvironmentVariablesArgs build() {
            if ($.value == null) {
                throw new MissingRequiredPropertyException("SmarthookEnvironmentVariablesArgs", "value");
            }
            return $;
        }
    }

}
