// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export function getActionsValues(args: GetActionsValuesArgs, opts?: pulumi.InvokeOptions): Promise<GetActionsValuesResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("onelogin:apps/getActionsValues:getActionsValues", {
        "actionsId": args.actionsId,
        "appsId": args.appsId,
        "filters": args.filters,
        "name": args.name,
        "value": args.value,
    }, opts);
}

/**
 * A collection of arguments for invoking getActionsValues.
 */
export interface GetActionsValuesArgs {
    actionsId: string;
    appsId: string;
    filters?: inputs.apps.GetActionsValuesFilter[];
    name?: string;
    value?: string;
}

/**
 * A collection of values returned by getActionsValues.
 */
export interface GetActionsValuesResult {
    readonly actionsId: string;
    readonly appsId: string;
    readonly filters?: outputs.apps.GetActionsValuesFilter[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly value: string;
}
export function getActionsValuesOutput(args: GetActionsValuesOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetActionsValuesResult> {
    return pulumi.output(args).apply((a: any) => getActionsValues(a, opts))
}

/**
 * A collection of arguments for invoking getActionsValues.
 */
export interface GetActionsValuesOutputArgs {
    actionsId: pulumi.Input<string>;
    appsId: pulumi.Input<string>;
    filters?: pulumi.Input<pulumi.Input<inputs.apps.GetActionsValuesFilterArgs>[]>;
    name?: pulumi.Input<string>;
    value?: pulumi.Input<string>;
}
