// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export function getRulesInstance(args: GetRulesInstanceArgs, opts?: pulumi.InvokeOptions): Promise<GetRulesInstanceResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("onelogin:apps/getRulesInstance:getRulesInstance", {
        "actions": args.actions,
        "appsId": args.appsId,
        "conditions": args.conditions,
        "enabled": args.enabled,
        "id": args.id,
        "match": args.match,
        "name": args.name,
        "position": args.position,
    }, opts);
}

/**
 * A collection of arguments for invoking getRulesInstance.
 */
export interface GetRulesInstanceArgs {
    actions?: inputs.apps.GetRulesInstanceAction[];
    appsId: string;
    conditions?: inputs.apps.GetRulesInstanceCondition[];
    enabled?: boolean;
    id: string;
    match?: string;
    name?: string;
    position?: number;
}

/**
 * A collection of values returned by getRulesInstance.
 */
export interface GetRulesInstanceResult {
    readonly actions: outputs.apps.GetRulesInstanceAction[];
    readonly appsId: string;
    readonly conditions: outputs.apps.GetRulesInstanceCondition[];
    readonly enabled: boolean;
    readonly id: string;
    readonly match: string;
    readonly name: string;
    readonly position: number;
}
export function getRulesInstanceOutput(args: GetRulesInstanceOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRulesInstanceResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("onelogin:apps/getRulesInstance:getRulesInstance", {
        "actions": args.actions,
        "appsId": args.appsId,
        "conditions": args.conditions,
        "enabled": args.enabled,
        "id": args.id,
        "match": args.match,
        "name": args.name,
        "position": args.position,
    }, opts);
}

/**
 * A collection of arguments for invoking getRulesInstance.
 */
export interface GetRulesInstanceOutputArgs {
    actions?: pulumi.Input<pulumi.Input<inputs.apps.GetRulesInstanceActionArgs>[]>;
    appsId: pulumi.Input<string>;
    conditions?: pulumi.Input<pulumi.Input<inputs.apps.GetRulesInstanceConditionArgs>[]>;
    enabled?: pulumi.Input<boolean>;
    id: pulumi.Input<string>;
    match?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    position?: pulumi.Input<number>;
}
