// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Onelogin.Outputs
{

    [OutputType]
    public sealed class SmartHookOption
    {
        /// <summary>
        /// When true an ip to location lookup is done and the location info is passed in the context. Only applies authentication time hooks. E.g. pre-authentication, user-migration. Default false
        /// </summary>
        public readonly bool? LocationEnabled;
        public readonly bool? MfaDeviceInfoEnabled;
        /// <summary>
        /// When true a risk score and risk reasons will be passed in the context. Only applies authentication time hooks. E.g. pre-authentication, user-migration. Default false
        /// </summary>
        public readonly bool? RiskEnabled;

        [OutputConstructor]
        private SmartHookOption(
            bool? locationEnabled,

            bool? mfaDeviceInfoEnabled,

            bool? riskEnabled)
        {
            LocationEnabled = locationEnabled;
            MfaDeviceInfoEnabled = mfaDeviceInfoEnabled;
            RiskEnabled = riskEnabled;
        }
    }
}
