// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package onelogin

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupUsers(ctx *pulumi.Context, args *LookupUsersArgs, opts ...pulumi.InvokeOption) (*LookupUsersResult, error) {
	var rv LookupUsersResult
	err := ctx.Invoke("onelogin:index/getUsers:getUsers", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getUsers.
type LookupUsersArgs struct {
	DirectoryId    *int    `pulumi:"directoryId"`
	ExternalId     *int    `pulumi:"externalId"`
	Firstname      *string `pulumi:"firstname"`
	Lastname       *string `pulumi:"lastname"`
	Samaccountname *string `pulumi:"samaccountname"`
	UserId         *string `pulumi:"userId"`
	Username       *string `pulumi:"username"`
}

// A collection of values returned by getUsers.
type LookupUsersResult struct {
	DirectoryId *int    `pulumi:"directoryId"`
	ExternalId  *int    `pulumi:"externalId"`
	Firstname   *string `pulumi:"firstname"`
	// The provider-assigned unique ID for this managed resource.
	Id             string   `pulumi:"id"`
	Ids            []string `pulumi:"ids"`
	Lastname       *string  `pulumi:"lastname"`
	Samaccountname *string  `pulumi:"samaccountname"`
	UserId         *string  `pulumi:"userId"`
	Username       *string  `pulumi:"username"`
}
