// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package onelogin

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Returns User IDs matching the given attributes.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-onelogin/sdk/go/onelogin"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		_, err := onelogin.GetUsers(ctx, &GetUsersArgs{
// 			Firstname: pulumi.StringRef("tom"),
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
func GetUsers(ctx *pulumi.Context, args *GetUsersArgs, opts ...pulumi.InvokeOption) (*GetUsersResult, error) {
	var rv GetUsersResult
	err := ctx.Invoke("onelogin:index/getUsers:getUsers", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getUsers.
type GetUsersArgs struct {
	// The user's directory_id
	DirectoryId *int `pulumi:"directoryId"`
	// The user's external_id
	ExternalId *int `pulumi:"externalId"`
	// The user's first name
	Firstname *string `pulumi:"firstname"`
	// The user's last name
	Lastname *string `pulumi:"lastname"`
	// The user's samaccount name
	Samaccountname *string `pulumi:"samaccountname"`
	UserId         *string `pulumi:"userId"`
	// The user's username.
	Username *string `pulumi:"username"`
}

// A collection of values returned by getUsers.
type GetUsersResult struct {
	DirectoryId *int    `pulumi:"directoryId"`
	ExternalId  *int    `pulumi:"externalId"`
	Firstname   *string `pulumi:"firstname"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// List of user's id
	Ids            []string `pulumi:"ids"`
	Lastname       *string  `pulumi:"lastname"`
	Samaccountname *string  `pulumi:"samaccountname"`
	UserId         *string  `pulumi:"userId"`
	Username       *string  `pulumi:"username"`
}

func GetUsersOutput(ctx *pulumi.Context, args GetUsersOutputArgs, opts ...pulumi.InvokeOption) GetUsersResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetUsersResult, error) {
			args := v.(GetUsersArgs)
			r, err := GetUsers(ctx, &args, opts...)
			var s GetUsersResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetUsersResultOutput)
}

// A collection of arguments for invoking getUsers.
type GetUsersOutputArgs struct {
	// The user's directory_id
	DirectoryId pulumi.IntPtrInput `pulumi:"directoryId"`
	// The user's external_id
	ExternalId pulumi.IntPtrInput `pulumi:"externalId"`
	// The user's first name
	Firstname pulumi.StringPtrInput `pulumi:"firstname"`
	// The user's last name
	Lastname pulumi.StringPtrInput `pulumi:"lastname"`
	// The user's samaccount name
	Samaccountname pulumi.StringPtrInput `pulumi:"samaccountname"`
	UserId         pulumi.StringPtrInput `pulumi:"userId"`
	// The user's username.
	Username pulumi.StringPtrInput `pulumi:"username"`
}

func (GetUsersOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetUsersArgs)(nil)).Elem()
}

// A collection of values returned by getUsers.
type GetUsersResultOutput struct{ *pulumi.OutputState }

func (GetUsersResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetUsersResult)(nil)).Elem()
}

func (o GetUsersResultOutput) ToGetUsersResultOutput() GetUsersResultOutput {
	return o
}

func (o GetUsersResultOutput) ToGetUsersResultOutputWithContext(ctx context.Context) GetUsersResultOutput {
	return o
}

func (o GetUsersResultOutput) DirectoryId() pulumi.IntPtrOutput {
	return o.ApplyT(func(v GetUsersResult) *int { return v.DirectoryId }).(pulumi.IntPtrOutput)
}

func (o GetUsersResultOutput) ExternalId() pulumi.IntPtrOutput {
	return o.ApplyT(func(v GetUsersResult) *int { return v.ExternalId }).(pulumi.IntPtrOutput)
}

func (o GetUsersResultOutput) Firstname() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetUsersResult) *string { return v.Firstname }).(pulumi.StringPtrOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetUsersResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetUsersResult) string { return v.Id }).(pulumi.StringOutput)
}

// List of user's id
func (o GetUsersResultOutput) Ids() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetUsersResult) []string { return v.Ids }).(pulumi.StringArrayOutput)
}

func (o GetUsersResultOutput) Lastname() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetUsersResult) *string { return v.Lastname }).(pulumi.StringPtrOutput)
}

func (o GetUsersResultOutput) Samaccountname() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetUsersResult) *string { return v.Samaccountname }).(pulumi.StringPtrOutput)
}

func (o GetUsersResultOutput) UserId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetUsersResult) *string { return v.UserId }).(pulumi.StringPtrOutput)
}

func (o GetUsersResultOutput) Username() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetUsersResult) *string { return v.Username }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetUsersResultOutput{})
}
