// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package onelogin

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Rule struct {
	pulumi.CustomResourceState

	Description pulumi.StringPtrOutput `pulumi:"description"`
	// A list of IP addresses or country codes or names to evaluate against each event.
	Filters pulumi.StringArrayOutput `pulumi:"filters"`
	// The name of this rule
	Name pulumi.StringOutput `pulumi:"name"`
	// Used for targeting custom rules based on a group of people, customers, accounts, or even a single user.
	Source RuleSourcePtrOutput `pulumi:"source"`
	// The target parameter that will be used when evaluating the rule against an incoming event.
	Target pulumi.StringPtrOutput `pulumi:"target"`
	// The type parameter specifies the type of rule that will be created.
	Type pulumi.StringPtrOutput `pulumi:"type"`
}

// NewRule registers a new resource with the given unique name, arguments, and options.
func NewRule(ctx *pulumi.Context,
	name string, args *RuleArgs, opts ...pulumi.ResourceOption) (*Rule, error) {
	if args == nil {
		args = &RuleArgs{}
	}

	var resource Rule
	err := ctx.RegisterResource("onelogin:index/rule:Rule", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetRule gets an existing Rule resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetRule(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *RuleState, opts ...pulumi.ResourceOption) (*Rule, error) {
	var resource Rule
	err := ctx.ReadResource("onelogin:index/rule:Rule", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Rule resources.
type ruleState struct {
	Description *string `pulumi:"description"`
	// A list of IP addresses or country codes or names to evaluate against each event.
	Filters []string `pulumi:"filters"`
	// The name of this rule
	Name *string `pulumi:"name"`
	// Used for targeting custom rules based on a group of people, customers, accounts, or even a single user.
	Source *RuleSource `pulumi:"source"`
	// The target parameter that will be used when evaluating the rule against an incoming event.
	Target *string `pulumi:"target"`
	// The type parameter specifies the type of rule that will be created.
	Type *string `pulumi:"type"`
}

type RuleState struct {
	Description pulumi.StringPtrInput
	// A list of IP addresses or country codes or names to evaluate against each event.
	Filters pulumi.StringArrayInput
	// The name of this rule
	Name pulumi.StringPtrInput
	// Used for targeting custom rules based on a group of people, customers, accounts, or even a single user.
	Source RuleSourcePtrInput
	// The target parameter that will be used when evaluating the rule against an incoming event.
	Target pulumi.StringPtrInput
	// The type parameter specifies the type of rule that will be created.
	Type pulumi.StringPtrInput
}

func (RuleState) ElementType() reflect.Type {
	return reflect.TypeOf((*ruleState)(nil)).Elem()
}

type ruleArgs struct {
	Description *string `pulumi:"description"`
	// A list of IP addresses or country codes or names to evaluate against each event.
	Filters []string `pulumi:"filters"`
	// The name of this rule
	Name *string `pulumi:"name"`
	// Used for targeting custom rules based on a group of people, customers, accounts, or even a single user.
	Source *RuleSource `pulumi:"source"`
	// The target parameter that will be used when evaluating the rule against an incoming event.
	Target *string `pulumi:"target"`
	// The type parameter specifies the type of rule that will be created.
	Type *string `pulumi:"type"`
}

// The set of arguments for constructing a Rule resource.
type RuleArgs struct {
	Description pulumi.StringPtrInput
	// A list of IP addresses or country codes or names to evaluate against each event.
	Filters pulumi.StringArrayInput
	// The name of this rule
	Name pulumi.StringPtrInput
	// Used for targeting custom rules based on a group of people, customers, accounts, or even a single user.
	Source RuleSourcePtrInput
	// The target parameter that will be used when evaluating the rule against an incoming event.
	Target pulumi.StringPtrInput
	// The type parameter specifies the type of rule that will be created.
	Type pulumi.StringPtrInput
}

func (RuleArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ruleArgs)(nil)).Elem()
}

type RuleInput interface {
	pulumi.Input

	ToRuleOutput() RuleOutput
	ToRuleOutputWithContext(ctx context.Context) RuleOutput
}

func (*Rule) ElementType() reflect.Type {
	return reflect.TypeOf((**Rule)(nil)).Elem()
}

func (i *Rule) ToRuleOutput() RuleOutput {
	return i.ToRuleOutputWithContext(context.Background())
}

func (i *Rule) ToRuleOutputWithContext(ctx context.Context) RuleOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RuleOutput)
}

// RuleArrayInput is an input type that accepts RuleArray and RuleArrayOutput values.
// You can construct a concrete instance of `RuleArrayInput` via:
//
//	RuleArray{ RuleArgs{...} }
type RuleArrayInput interface {
	pulumi.Input

	ToRuleArrayOutput() RuleArrayOutput
	ToRuleArrayOutputWithContext(context.Context) RuleArrayOutput
}

type RuleArray []RuleInput

func (RuleArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Rule)(nil)).Elem()
}

func (i RuleArray) ToRuleArrayOutput() RuleArrayOutput {
	return i.ToRuleArrayOutputWithContext(context.Background())
}

func (i RuleArray) ToRuleArrayOutputWithContext(ctx context.Context) RuleArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RuleArrayOutput)
}

// RuleMapInput is an input type that accepts RuleMap and RuleMapOutput values.
// You can construct a concrete instance of `RuleMapInput` via:
//
//	RuleMap{ "key": RuleArgs{...} }
type RuleMapInput interface {
	pulumi.Input

	ToRuleMapOutput() RuleMapOutput
	ToRuleMapOutputWithContext(context.Context) RuleMapOutput
}

type RuleMap map[string]RuleInput

func (RuleMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Rule)(nil)).Elem()
}

func (i RuleMap) ToRuleMapOutput() RuleMapOutput {
	return i.ToRuleMapOutputWithContext(context.Background())
}

func (i RuleMap) ToRuleMapOutputWithContext(ctx context.Context) RuleMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RuleMapOutput)
}

type RuleOutput struct{ *pulumi.OutputState }

func (RuleOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Rule)(nil)).Elem()
}

func (o RuleOutput) ToRuleOutput() RuleOutput {
	return o
}

func (o RuleOutput) ToRuleOutputWithContext(ctx context.Context) RuleOutput {
	return o
}

func (o RuleOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Rule) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// A list of IP addresses or country codes or names to evaluate against each event.
func (o RuleOutput) Filters() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Rule) pulumi.StringArrayOutput { return v.Filters }).(pulumi.StringArrayOutput)
}

// The name of this rule
func (o RuleOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Rule) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Used for targeting custom rules based on a group of people, customers, accounts, or even a single user.
func (o RuleOutput) Source() RuleSourcePtrOutput {
	return o.ApplyT(func(v *Rule) RuleSourcePtrOutput { return v.Source }).(RuleSourcePtrOutput)
}

// The target parameter that will be used when evaluating the rule against an incoming event.
func (o RuleOutput) Target() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Rule) pulumi.StringPtrOutput { return v.Target }).(pulumi.StringPtrOutput)
}

// The type parameter specifies the type of rule that will be created.
func (o RuleOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Rule) pulumi.StringPtrOutput { return v.Type }).(pulumi.StringPtrOutput)
}

type RuleArrayOutput struct{ *pulumi.OutputState }

func (RuleArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Rule)(nil)).Elem()
}

func (o RuleArrayOutput) ToRuleArrayOutput() RuleArrayOutput {
	return o
}

func (o RuleArrayOutput) ToRuleArrayOutputWithContext(ctx context.Context) RuleArrayOutput {
	return o
}

func (o RuleArrayOutput) Index(i pulumi.IntInput) RuleOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Rule {
		return vs[0].([]*Rule)[vs[1].(int)]
	}).(RuleOutput)
}

type RuleMapOutput struct{ *pulumi.OutputState }

func (RuleMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Rule)(nil)).Elem()
}

func (o RuleMapOutput) ToRuleMapOutput() RuleMapOutput {
	return o
}

func (o RuleMapOutput) ToRuleMapOutputWithContext(ctx context.Context) RuleMapOutput {
	return o
}

func (o RuleMapOutput) MapIndex(k pulumi.StringInput) RuleOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Rule {
		return vs[0].(map[string]*Rule)[vs[1].(string)]
	}).(RuleOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*RuleInput)(nil)).Elem(), &Rule{})
	pulumi.RegisterInputType(reflect.TypeOf((*RuleArrayInput)(nil)).Elem(), RuleArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*RuleMapInput)(nil)).Elem(), RuleMap{})
	pulumi.RegisterOutputType(RuleOutput{})
	pulumi.RegisterOutputType(RuleArrayOutput{})
	pulumi.RegisterOutputType(RuleMapOutput{})
}
