// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.onelogin.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.onelogin.inputs.GetAppsParametersGroupsArgs;
import java.util.Objects;


public final class GetAppsParametersArgs extends com.pulumi.resources.ResourceArgs {

    public static final GetAppsParametersArgs Empty = new GetAppsParametersArgs();

    @Import(name="groups", required=true)
    private Output<GetAppsParametersGroupsArgs> groups;

    public Output<GetAppsParametersGroupsArgs> groups() {
        return this.groups;
    }

    private GetAppsParametersArgs() {}

    private GetAppsParametersArgs(GetAppsParametersArgs $) {
        this.groups = $.groups;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetAppsParametersArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetAppsParametersArgs $;

        public Builder() {
            $ = new GetAppsParametersArgs();
        }

        public Builder(GetAppsParametersArgs defaults) {
            $ = new GetAppsParametersArgs(Objects.requireNonNull(defaults));
        }

        public Builder groups(Output<GetAppsParametersGroupsArgs> groups) {
            $.groups = groups;
            return this;
        }

        public Builder groups(GetAppsParametersGroupsArgs groups) {
            return groups(Output.of(groups));
        }

        public GetAppsParametersArgs build() {
            $.groups = Objects.requireNonNull($.groups, "expected parameter 'groups' to be non-null");
            return $;
        }
    }

}
