// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.onelogin.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.onelogin.inputs.GetAuthServersInstanceConfiguration;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetAuthServersInstancePlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetAuthServersInstancePlainArgs Empty = new GetAuthServersInstancePlainArgs();

    @Import(name="configuration")
    private @Nullable GetAuthServersInstanceConfiguration configuration;

    public Optional<GetAuthServersInstanceConfiguration> configuration() {
        return Optional.ofNullable(this.configuration);
    }

    @Import(name="description")
    private @Nullable String description;

    public Optional<String> description() {
        return Optional.ofNullable(this.description);
    }

    @Import(name="id", required=true)
    private String id;

    public String id() {
        return this.id;
    }

    @Import(name="name")
    private @Nullable String name;

    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }

    private GetAuthServersInstancePlainArgs() {}

    private GetAuthServersInstancePlainArgs(GetAuthServersInstancePlainArgs $) {
        this.configuration = $.configuration;
        this.description = $.description;
        this.id = $.id;
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetAuthServersInstancePlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetAuthServersInstancePlainArgs $;

        public Builder() {
            $ = new GetAuthServersInstancePlainArgs();
        }

        public Builder(GetAuthServersInstancePlainArgs defaults) {
            $ = new GetAuthServersInstancePlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder configuration(@Nullable GetAuthServersInstanceConfiguration configuration) {
            $.configuration = configuration;
            return this;
        }

        public Builder description(@Nullable String description) {
            $.description = description;
            return this;
        }

        public Builder id(String id) {
            $.id = id;
            return this;
        }

        public Builder name(@Nullable String name) {
            $.name = name;
            return this;
        }

        public GetAuthServersInstancePlainArgs build() {
            if ($.id == null) {
                throw new MissingRequiredPropertyException("GetAuthServersInstancePlainArgs", "id");
            }
            return $;
        }
    }

}
