// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.onelogin.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.onelogin.inputs.GetAppsSsoCertificate;
import java.lang.String;
import java.util.Objects;


public final class GetAppsSso extends com.pulumi.resources.InvokeArgs {

    public static final GetAppsSso Empty = new GetAppsSso();

    @Import(name="acsUrl", required=true)
    private String acsUrl;

    public String acsUrl() {
        return this.acsUrl;
    }

    @Import(name="certificate", required=true)
    private GetAppsSsoCertificate certificate;

    public GetAppsSsoCertificate certificate() {
        return this.certificate;
    }

    @Import(name="clientId", required=true)
    private String clientId;

    public String clientId() {
        return this.clientId;
    }

    @Import(name="clientSecret", required=true)
    private String clientSecret;

    public String clientSecret() {
        return this.clientSecret;
    }

    @Import(name="issuer", required=true)
    private String issuer;

    public String issuer() {
        return this.issuer;
    }

    @Import(name="metadataUrl", required=true)
    private String metadataUrl;

    public String metadataUrl() {
        return this.metadataUrl;
    }

    private GetAppsSso() {}

    private GetAppsSso(GetAppsSso $) {
        this.acsUrl = $.acsUrl;
        this.certificate = $.certificate;
        this.clientId = $.clientId;
        this.clientSecret = $.clientSecret;
        this.issuer = $.issuer;
        this.metadataUrl = $.metadataUrl;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetAppsSso defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetAppsSso $;

        public Builder() {
            $ = new GetAppsSso();
        }

        public Builder(GetAppsSso defaults) {
            $ = new GetAppsSso(Objects.requireNonNull(defaults));
        }

        public Builder acsUrl(String acsUrl) {
            $.acsUrl = acsUrl;
            return this;
        }

        public Builder certificate(GetAppsSsoCertificate certificate) {
            $.certificate = certificate;
            return this;
        }

        public Builder clientId(String clientId) {
            $.clientId = clientId;
            return this;
        }

        public Builder clientSecret(String clientSecret) {
            $.clientSecret = clientSecret;
            return this;
        }

        public Builder issuer(String issuer) {
            $.issuer = issuer;
            return this;
        }

        public Builder metadataUrl(String metadataUrl) {
            $.metadataUrl = metadataUrl;
            return this;
        }

        public GetAppsSso build() {
            if ($.acsUrl == null) {
                throw new MissingRequiredPropertyException("GetAppsSso", "acsUrl");
            }
            if ($.certificate == null) {
                throw new MissingRequiredPropertyException("GetAppsSso", "certificate");
            }
            if ($.clientId == null) {
                throw new MissingRequiredPropertyException("GetAppsSso", "clientId");
            }
            if ($.clientSecret == null) {
                throw new MissingRequiredPropertyException("GetAppsSso", "clientSecret");
            }
            if ($.issuer == null) {
                throw new MissingRequiredPropertyException("GetAppsSso", "issuer");
            }
            if ($.metadataUrl == null) {
                throw new MissingRequiredPropertyException("GetAppsSso", "metadataUrl");
            }
            return $;
        }
    }

}
