// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.onelogin.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.List;
import java.util.Objects;


public final class GetPrivilegesInstancePrivilegeStatementArgs extends com.pulumi.resources.ResourceArgs {

    public static final GetPrivilegesInstancePrivilegeStatementArgs Empty = new GetPrivilegesInstancePrivilegeStatementArgs();

    @Import(name="actions", required=true)
    private Output<List<String>> actions;

    public Output<List<String>> actions() {
        return this.actions;
    }

    @Import(name="effect", required=true)
    private Output<String> effect;

    public Output<String> effect() {
        return this.effect;
    }

    @Import(name="scopes", required=true)
    private Output<List<String>> scopes;

    public Output<List<String>> scopes() {
        return this.scopes;
    }

    private GetPrivilegesInstancePrivilegeStatementArgs() {}

    private GetPrivilegesInstancePrivilegeStatementArgs(GetPrivilegesInstancePrivilegeStatementArgs $) {
        this.actions = $.actions;
        this.effect = $.effect;
        this.scopes = $.scopes;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetPrivilegesInstancePrivilegeStatementArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetPrivilegesInstancePrivilegeStatementArgs $;

        public Builder() {
            $ = new GetPrivilegesInstancePrivilegeStatementArgs();
        }

        public Builder(GetPrivilegesInstancePrivilegeStatementArgs defaults) {
            $ = new GetPrivilegesInstancePrivilegeStatementArgs(Objects.requireNonNull(defaults));
        }

        public Builder actions(Output<List<String>> actions) {
            $.actions = actions;
            return this;
        }

        public Builder actions(List<String> actions) {
            return actions(Output.of(actions));
        }

        public Builder actions(String... actions) {
            return actions(List.of(actions));
        }

        public Builder effect(Output<String> effect) {
            $.effect = effect;
            return this;
        }

        public Builder effect(String effect) {
            return effect(Output.of(effect));
        }

        public Builder scopes(Output<List<String>> scopes) {
            $.scopes = scopes;
            return this;
        }

        public Builder scopes(List<String> scopes) {
            return scopes(Output.of(scopes));
        }

        public Builder scopes(String... scopes) {
            return scopes(List.of(scopes));
        }

        public GetPrivilegesInstancePrivilegeStatementArgs build() {
            $.actions = Objects.requireNonNull($.actions, "expected parameter 'actions' to be non-null");
            $.effect = Objects.requireNonNull($.effect, "expected parameter 'effect' to be non-null");
            $.scopes = Objects.requireNonNull($.scopes, "expected parameter 'scopes' to be non-null");
            return $;
        }
    }

}
