// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Onelogin.Apps.Outputs
{

    [OutputType]
    public sealed class GetRulesInstanceActionResult
    {
        /// <summary>
        /// The action to apply
        /// </summary>
        public readonly string Action;
        /// <summary>
        /// Only applicable to provisioned and set_* actions. Items in the array will be a plain text string or valid value for the selected action.
        /// </summary>
        public readonly ImmutableArray<string> Values;

        [OutputConstructor]
        private GetRulesInstanceActionResult(
            string action,

            ImmutableArray<string> values)
        {
            Action = action;
            Values = values;
        }
    }
}
