// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.onelogin.apps.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;


public final class GetRulesCondition extends com.pulumi.resources.InvokeArgs {

    public static final GetRulesCondition Empty = new GetRulesCondition();

    @Import(name="operator", required=true)
    private String operator;

    public String operator() {
        return this.operator;
    }

    @Import(name="source", required=true)
    private String source;

    public String source() {
        return this.source;
    }

    @Import(name="value", required=true)
    private String value;

    public String value() {
        return this.value;
    }

    private GetRulesCondition() {}

    private GetRulesCondition(GetRulesCondition $) {
        this.operator = $.operator;
        this.source = $.source;
        this.value = $.value;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetRulesCondition defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetRulesCondition $;

        public Builder() {
            $ = new GetRulesCondition();
        }

        public Builder(GetRulesCondition defaults) {
            $ = new GetRulesCondition(Objects.requireNonNull(defaults));
        }

        public Builder operator(String operator) {
            $.operator = operator;
            return this;
        }

        public Builder source(String source) {
            $.source = source;
            return this;
        }

        public Builder value(String value) {
            $.value = value;
            return this;
        }

        public GetRulesCondition build() {
            $.operator = Objects.requireNonNull($.operator, "expected parameter 'operator' to be non-null");
            $.source = Objects.requireNonNull($.source, "expected parameter 'source' to be non-null");
            $.value = Objects.requireNonNull($.value, "expected parameter 'value' to be non-null");
            return $;
        }
    }

}
