// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.onelogin.apps.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetRulesInstanceCondition extends com.pulumi.resources.InvokeArgs {

    public static final GetRulesInstanceCondition Empty = new GetRulesInstanceCondition();

    /**
     * A valid operator for the selected condition source
     * 
     */
    @Import(name="operator", required=true)
    private String operator;

    /**
     * @return A valid operator for the selected condition source
     * 
     */
    public String operator() {
        return this.operator;
    }

    /**
     * source field to check.
     * 
     */
    @Import(name="source", required=true)
    private String source;

    /**
     * @return source field to check.
     * 
     */
    public String source() {
        return this.source;
    }

    /**
     * A plain text string or valid value for the selected  condition source
     * 
     */
    @Import(name="value", required=true)
    private String value;

    /**
     * @return A plain text string or valid value for the selected  condition source
     * 
     */
    public String value() {
        return this.value;
    }

    private GetRulesInstanceCondition() {}

    private GetRulesInstanceCondition(GetRulesInstanceCondition $) {
        this.operator = $.operator;
        this.source = $.source;
        this.value = $.value;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetRulesInstanceCondition defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetRulesInstanceCondition $;

        public Builder() {
            $ = new GetRulesInstanceCondition();
        }

        public Builder(GetRulesInstanceCondition defaults) {
            $ = new GetRulesInstanceCondition(Objects.requireNonNull(defaults));
        }

        /**
         * @param operator A valid operator for the selected condition source
         * 
         * @return builder
         * 
         */
        public Builder operator(String operator) {
            $.operator = operator;
            return this;
        }

        /**
         * @param source source field to check.
         * 
         * @return builder
         * 
         */
        public Builder source(String source) {
            $.source = source;
            return this;
        }

        /**
         * @param value A plain text string or valid value for the selected  condition source
         * 
         * @return builder
         * 
         */
        public Builder value(String value) {
            $.value = value;
            return this;
        }

        public GetRulesInstanceCondition build() {
            if ($.operator == null) {
                throw new MissingRequiredPropertyException("GetRulesInstanceCondition", "operator");
            }
            if ($.source == null) {
                throw new MissingRequiredPropertyException("GetRulesInstanceCondition", "source");
            }
            if ($.value == null) {
                throw new MissingRequiredPropertyException("GetRulesInstanceCondition", "value");
            }
            return $;
        }
    }

}
