// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Onelogin.Inputs
{

    public sealed class ProviderEndpointArgs : global::Pulumi.ResourceArgs
    {
        [Input("apps")]
        public Input<string>? Apps { get; set; }

        [Input("rules")]
        public Input<string>? Rules { get; set; }

        [Input("users")]
        public Input<string>? Users { get; set; }

        public ProviderEndpointArgs()
        {
        }
        public static new ProviderEndpointArgs Empty => new ProviderEndpointArgs();
    }
}
