// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.onelogin.apps;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.onelogin.Utilities;
import com.pulumi.onelogin.apps.RulesArgs;
import com.pulumi.onelogin.apps.inputs.RulesState;
import com.pulumi.onelogin.apps.outputs.RulesAction;
import com.pulumi.onelogin.apps.outputs.RulesCondition;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="onelogin:apps/rules:Rules")
public class Rules extends com.pulumi.resources.CustomResource {
    @Export(name="actions", refs={List.class,RulesAction.class}, tree="[0,1]")
    private Output</* @Nullable */ List<RulesAction>> actions;

    public Output<Optional<List<RulesAction>>> actions() {
        return Codegen.optional(this.actions);
    }
    @Export(name="appId", refs={String.class}, tree="[0]")
    private Output<String> appId;

    public Output<String> appId() {
        return this.appId;
    }
    @Export(name="conditions", refs={List.class,RulesCondition.class}, tree="[0,1]")
    private Output</* @Nullable */ List<RulesCondition>> conditions;

    public Output<Optional<List<RulesCondition>>> conditions() {
        return Codegen.optional(this.conditions);
    }
    @Export(name="enabled", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> enabled;

    public Output<Optional<Boolean>> enabled() {
        return Codegen.optional(this.enabled);
    }
    @Export(name="match", refs={String.class}, tree="[0]")
    private Output<String> match;

    public Output<String> match() {
        return this.match;
    }
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    public Output<String> name() {
        return this.name;
    }
    @Export(name="position", refs={Integer.class}, tree="[0]")
    private Output<Integer> position;

    public Output<Integer> position() {
        return this.position;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Rules(java.lang.String name) {
        this(name, RulesArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Rules(java.lang.String name, RulesArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Rules(java.lang.String name, RulesArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("onelogin:apps/rules:Rules", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Rules(java.lang.String name, Output<java.lang.String> id, @Nullable RulesState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("onelogin:apps/rules:Rules", name, state, makeResourceOptions(options, id), false);
    }

    private static RulesArgs makeArgs(RulesArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? RulesArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Rules get(java.lang.String name, Output<java.lang.String> id, @Nullable RulesState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Rules(name, id, state, options);
    }
}
