// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as onelogin from "@pulumi/onelogin";
 *
 * const example = new onelogin.AppRoleAttachment("example", {
 *     appId: onelogin_saml_apps.saml.id,
 *     roleId: 12345,
 * });
 * ```
 *
 * ## Import
 *
 * An App Role Attachment cannot be imported at this time.
 */
export class AppRoleAttachment extends pulumi.CustomResource {
    /**
     * Get an existing AppRoleAttachment resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AppRoleAttachmentState, opts?: pulumi.CustomResourceOptions): AppRoleAttachment {
        return new AppRoleAttachment(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'onelogin:index/appRoleAttachment:AppRoleAttachment';

    /**
     * Returns true if the given object is an instance of AppRoleAttachment.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AppRoleAttachment {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AppRoleAttachment.__pulumiType;
    }

    /**
     * The id of the App resource to which the role should belong.
     */
    public readonly appId!: pulumi.Output<number>;
    /**
     * The id of the Role being attached to the App.
     */
    public readonly roleId!: pulumi.Output<number>;

    /**
     * Create a AppRoleAttachment resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AppRoleAttachmentArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AppRoleAttachmentArgs | AppRoleAttachmentState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AppRoleAttachmentState | undefined;
            resourceInputs["appId"] = state ? state.appId : undefined;
            resourceInputs["roleId"] = state ? state.roleId : undefined;
        } else {
            const args = argsOrState as AppRoleAttachmentArgs | undefined;
            if ((!args || args.appId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'appId'");
            }
            if ((!args || args.roleId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'roleId'");
            }
            resourceInputs["appId"] = args ? args.appId : undefined;
            resourceInputs["roleId"] = args ? args.roleId : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AppRoleAttachment.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering AppRoleAttachment resources.
 */
export interface AppRoleAttachmentState {
    /**
     * The id of the App resource to which the role should belong.
     */
    appId?: pulumi.Input<number>;
    /**
     * The id of the Role being attached to the App.
     */
    roleId?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a AppRoleAttachment resource.
 */
export interface AppRoleAttachmentArgs {
    /**
     * The id of the App resource to which the role should belong.
     */
    appId: pulumi.Input<number>;
    /**
     * The id of the Role being attached to the App.
     */
    roleId: pulumi.Input<number>;
}
