// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Onelogin.Rules
{
    public static class GetInstance
    {
        public static Task<GetInstanceResult> InvokeAsync(GetInstanceArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetInstanceResult>("onelogin:rules/getInstance:getInstance", args ?? new GetInstanceArgs(), options.WithDefaults());

        public static Output<GetInstanceResult> Invoke(GetInstanceInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetInstanceResult>("onelogin:rules/getInstance:getInstance", args ?? new GetInstanceInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetInstanceArgs : global::Pulumi.InvokeArgs
    {
        [Input("description")]
        public string? Description { get; set; }

        [Input("filters")]
        private List<string>? _filters;
        public List<string> Filters
        {
            get => _filters ?? (_filters = new List<string>());
            set => _filters = value;
        }

        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        [Input("name")]
        public string? Name { get; set; }

        [Input("source")]
        public Inputs.GetInstanceSourceArgs? Source { get; set; }

        [Input("target")]
        public string? Target { get; set; }

        [Input("type")]
        public string? Type { get; set; }

        public GetInstanceArgs()
        {
        }
        public static new GetInstanceArgs Empty => new GetInstanceArgs();
    }

    public sealed class GetInstanceInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("filters")]
        private InputList<string>? _filters;
        public InputList<string> Filters
        {
            get => _filters ?? (_filters = new InputList<string>());
            set => _filters = value;
        }

        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("source")]
        public Input<Inputs.GetInstanceSourceInputArgs>? Source { get; set; }

        [Input("target")]
        public Input<string>? Target { get; set; }

        [Input("type")]
        public Input<string>? Type { get; set; }

        public GetInstanceInvokeArgs()
        {
        }
        public static new GetInstanceInvokeArgs Empty => new GetInstanceInvokeArgs();
    }


    [OutputType]
    public sealed class GetInstanceResult
    {
        public readonly string Description;
        public readonly ImmutableArray<string> Filters;
        public readonly string Id;
        public readonly string Name;
        public readonly Outputs.GetInstanceSourceResult Source;
        public readonly string Target;
        public readonly string Type;

        [OutputConstructor]
        private GetInstanceResult(
            string description,

            ImmutableArray<string> filters,

            string id,

            string name,

            Outputs.GetInstanceSourceResult source,

            string target,

            string type)
        {
            Description = description;
            Filters = filters;
            Id = id;
            Name = name;
            Source = source;
            Target = target;
            Type = type;
        }
    }
}
